// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kingsmen.DAL;

namespace kingsmen.Migrations
{
    [DbContext(typeof(CharacterContext))]
    [Migration("20200811043552_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("kingsmen.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Align")
                        .HasColumnType("TEXT");

                    b.Property<string>("Alive")
                        .HasColumnType("TEXT");

                    b.Property<int>("Appearances")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Eye")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstAppearanceDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FirstAppearanceYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GSM")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hair")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("PageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecretIdentity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sex")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
